<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $title ?></title>
<link rel="stylesheet" type="text/css" href="style.css" />
<!-- Google Analytics -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28079857-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
    <div id="top_menu">
                        <ul class="menu">
                            <li><a href="index.html" class="nav">home</a></li>
                            <li><a href="gallery/gallery1.html" class="nav">galería</a></li>
                            <li><a href="howto.html" class="nav">¿cómo se hacen?</a></li>
                            <li><a href="pedido.html" class="nav">hacer pedido</a></li>
                            <li><a href="contact.html" class="nav">contacto</a></li>
                            <li><a href="aboutus.html" class="nav">¿quién soy?</a></li>
                        </ul>
    </div>
    <div id="main_content">
        <div id="top_banner">
        <a href="index.html" target="_self"><img src="images/logo1.svg" width="600" height="131" alt="home" title="logo" border="0" class="logo" /></a>
        </div>
