<div id="page_content_right">
            <div class="title">
            Últimos tapices
            </div>
            <div class="content_text">
            Estos son algunos de los tapices que tenemos. Haz clic en 
            las fotos para ir a la ficha de cada tapiz, o visita <a href="gallery/gallery1.html" class="link">la galería</a> para verlos todos.
            </div>
            <div class="content_text">
            <a href="details/0001.html"><img src="http://carmentapices.temploiphone.com/images/Tapices/galeria (100x100)/0001.JPG" width="100" height="100"  alt="pic" title="pic" class="gallery" /></a>
            <a href="details/0002.html"><img src="http://carmentapices.temploiphone.com/images/Tapices/galeria (100x100)/0002.jpg" width="100" height="100"  alt="pic" title="pic" class="gallery" /></a>
            <a href="details/0003.html"><img src="http://carmentapices.temploiphone.com/images/Tapices/galeria (100x100)/0003.jpg" width="100" height="100"  alt="pic" title="pic" class="gallery" /></a>
            <a href="details/0004.html"><img src="http://carmentapices.temploiphone.com/images/Tapices/galeria (100x100)/0004.jpg" width="100" height="100"  alt="pic" title="pic" class="gallery" /></a>
            <a href="details/0005.html"><img src="http://carmentapices.temploiphone.com/images/Tapices/galeria (100x100)/0005.jpg" width="100" height="100"  alt="pic" title="pic" class="gallery" /></a>
            <a href="details/0006.html"><img src="http://carmentapices.temploiphone.com/images/Tapices/galeria (100x100)/0006.jpg" width="100" height="100"  alt="pic" title="pic" class="gallery" /></a>
            <a href="details/0007.html"><img src="http://carmentapices.temploiphone.com/images/Tapices/galeria (100x100)/0007.jpg" width="100" height="100"  alt="pic" title="pic" class="gallery" /></a>
            <a href="details/0008.html"><img src="http://carmentapices.temploiphone.com/images/Tapices/galeria (100x100)/0008.jpg" width="100" height="100"  alt="pic" title="pic" class="gallery" /></a>
            <a href="details/0009.html"><img src="http://carmentapices.temploiphone.com/images/Tapices/galeria (100x100)/0009.jpg" width="100" height="100"  alt="pic" title="pic" class="gallery" /></a>
            </div>
            <div class="more">
            <img src="images/more.jpg" width="20" height="20" alt="more" title="more" border="0" class="more" />
           <a href="gallery/gallery1.html" class="link_more"> Visitar galería</a>
            </div>
</div>
        
        
       


