<div id="page_bottom">
</div>
        
    </div>
    
<div id="footer">
<div id="footer_content">
	<div>
    <ul class="footer_menu">
                    
                        <li><a href="index.html" class="nav2">home</a></li>
                        <li><a href="gallery/gallery1.html" class="nav2">galería</a></li>
                        <li><a href="howto.html" class="nav2">¿cómo se hacen?</a></li>
                        <li><a href="pedido.html" class="nav2">hacer pedido</a></li>
                        <li><a href="contact.html" class="nav2">contacto</a></li>
                        <li><a href="aboutus.html" class="nav2">¿quién soy?</a></li>
                    </ul>
    </div>
    
    <div id="copyrights">
Plantilla de: Quartz Solution.&copy; All Rights Reserved 2007 <br/>
El contenido de esta web está bajo licencia Creative Commons<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/"><img alt="Licencia de Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-nd/3.0/80x15.png" /></a>
</div>
</div>

</div>


</body>
</html>
